server:
  port: ${PORT:8090}

spring:
  application:
    name: user-service

  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      max-size: 10
      initial-size: 2
      max-idle-time: 30s

  codec:
    max-in-memory-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: BASIC

firebase:
  credentials: ${FIREBASE_CREDENTIALS}

supabase:
  project-url: ${SUPABASE_PROJECT_URL}
  api-key: ${SUPABASE_API_KEY}
  bucket: ${SUPABASE_BUCKET}
  folder: ${SUPABASE_FOLDER}

logging:
  level:
    pe.edu.vallegrande.user_service: DEBUG
    io.r2dbc: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security.web.server: DEBUG
